import React from 'react';

export interface SearchItem {
  title: string;
  type: "College" | "Program" | "Course" | "Admission" | "Entrance" | "Scholarship" | "University" | "Trending";
}

export const searchDatabase: SearchItem[] = [
  // 1. COLLEGES (By Level & Location & Type)
  { title: "Best +2 Science Colleges in Kathmandu", type: "College" },
  { title: "Top +2 Management Colleges in Lalitpur", type: "College" },
  { title: "+2 Colleges Near Me", type: "College" },
  { title: "+2 Humanities Colleges in Nepal", type: "College" },
  { title: "+2 Law Colleges in Kathmandu", type: "College" },
  { title: "+2 Private Colleges in Kathmandu", type: "College" },
  { title: "Community / Government +2 Colleges", type: "College" },
  { title: "A-Level Colleges in Nepal", type: "College" },
  { title: "CTEVT Diploma Colleges in Kathmandu", type: "College" },
  { title: "Top Bachelor Degree Colleges", type: "College" },
  { title: "Master Degree Colleges in Nepal", type: "College" },
  { title: "Government Colleges for Bachelor in Kathmandu", type: "College" },
  
  // 2. COLLEGES (By Program/Faculty)
  { title: "BIT (Bachelor of Information Technology) Colleges", type: "College" },
  { title: "Best BCA Colleges in Nepal", type: "College" },
  { title: "BSc CSIT Colleges under TU", type: "College" },
  { title: "BBA Colleges in Kathmandu", type: "College" },
  { title: "Best BBA Colleges in Pokhara", type: "College" },
  { title: "BBM (Bachelor of Business Management) Colleges", type: "College" },
  { title: "Medical Colleges (MBBS/BDS) in Nepal", type: "College" },
  { title: "Engineering Colleges (BE Civil/Computer/IT)", type: "College" },
  { title: "Science Colleges in Nepal (BSc)", type: "College" },
  { title: "Management Colleges in Nepal", type: "College" },
  { title: "Nursing Colleges (BSc Nursing / PBN)", type: "College" },
  { title: "Law Colleges (BA LLB / LLB)", type: "College" },
  { title: "Agriculture / Forestry Colleges", type: "College" },
  { title: "Hotel Management (BHM) Colleges", type: "College" },

  // 3. PROGRAMS & COURSES
  { title: "BIT (Bachelor of Information Technology)", type: "Program" },
  { title: "BSc CSIT (Computer Science & IT)", type: "Program" },
  { title: "BBA (Bachelor of Business Administration)", type: "Program" },
  { title: "BCA (Bachelor of Computer Applications)", type: "Program" },
  { title: "MBBS (Bachelor of Medicine, Bachelor of Surgery)", type: "Program" },
  { title: "BE Computer Engineering", type: "Program" },
  { title: "BE Civil Engineering", type: "Program" },
  { title: "Diploma in Civil Engineering (CTEVT)", type: "Program" },
  { title: "Diploma in Computer Engineering (CTEVT)", type: "Program" },
  { title: "Staff Nurse (PCL Nursing) CTEVT", type: "Program" },
  { title: "Pharmacy (BPharm)", type: "Program" },
  { title: "Chartered Accountancy (CA) ICAN", type: "Course" },
  { title: "IELTS / PTE / TOEFL Preparation Classes", type: "Course" },
  { title: "Bridge Course for Post-SEE Students", type: "Course" },

  // 4. ADMISSIONS (Updates & Info)
  { title: "+2 Admission Open 2024/2025", type: "Admission" },
  { title: "TU BSc CSIT Admission Notice", type: "Admission" },
  { title: "KU BBA/BIT Admission Open", type: "Admission" },
  { title: "CTEVT Diploma/PCL Admission Notice", type: "Admission" },
  { title: "MBBS Admission in Medical Colleges", type: "Admission" },
  { title: "Admission in Government +2 Colleges", type: "Admission" },
  { title: "A-Level Admission Deadlines", type: "Admission" },
  { title: "Master's Degree (MBA/MBS) Admission TU", type: "Admission" },
  { title: "Foreign University Affiliate College Admissions", type: "Admission" },

  // 5. ENTRANCES (Exams & Preparation)
  { title: "CMAT Entrance Exam Preparation", type: "Entrance" },
  { title: "IOE (Institute of Engineering) Entrance Exam", type: "Entrance" },
  { title: "MECEE-BL (Medical Education Commission Entrance)", type: "Entrance" },
  { title: "KUUMAT (Kathmandu University Undergraduate Management)", type: "Entrance" },
  { title: "KUCAT (Kathmandu University Computer Based Test)", type: "Entrance" },
  { title: "St. Xavier's +2 Science Entrance Exam", type: "Entrance" },
  { title: "CTEVT Classified Scholarship Entrance Exam", type: "Entrance" },
  { title: "BSc CSIT Entrance Preparation Classes", type: "Entrance" },
  { title: "PU (Pokhara University) Entrance Exam", type: "Entrance" },
  { title: "Bridge Course / Entrance for +2 Science", type: "Entrance" },

  // 6. SCHOLARSHIPS
  { title: "MoE (Ministry of Education) Scholarships for MBBS/Engineering", type: "Scholarship" },
  { title: "CTEVT Classified Scholarship Programs", type: "Scholarship" },
  { title: "Mahatma Gandhi Scholarship for +2 Students", type: "Scholarship" },
  { title: "College-Based Merit Scholarships (+2 & Bachelor)", type: "Scholarship" },
  { title: "Entrance-Based Scholarships (CMAT/IOE Top Rankers)", type: "Scholarship" },
  { title: "School-Based Quota Scholarships", type: "Scholarship" },
  { title: "Institute-Based Entrance Scholarships", type: "Scholarship" },
  { title: "Australian Awards / Chevening Scholarships (For Masters)", type: "Scholarship" },
  { title: "Embassy of India Scholarships (Complex Selection)", type: "Scholarship" },

  // 7. UNIVERSITIES & RANKINGS
  { title: "Tribhuvan University (TU)", type: "University" },
  { title: "Kathmandu University (KU)", type: "University" },
  { title: "Pokhara University (PU)", type: "University" },
  { title: "Purbanchal University", type: "University" },
  { title: "Foreign Universities in Nepal (UK/US/AUS Affiliations)", type: "University" },
  { title: "London Metropolitan University Affiliated Colleges", type: "University" },
  { title: "University of the West of England (UWE) Colleges", type: "University" },
  { title: "University Rankings in Nepal", type: "University" },
  { title: "Top Ranked Engineering Colleges under TU", type: "University" },
  { title: "Best Ranked BBA Colleges by University", type: "University" },

  // A-Z
  { title: "Apex College (BBA/BCIS)", type: "College" },
  { title: "Agriculture (BSc. Ag) Colleges in Nepal", type: "College" },
  { title: "A-Level Scholarships & Financial Aid", type: "Scholarship" },
  { title: "Baneshwor Multiple Campus", type: "College" },
  { title: "BDS (Bachelor of Dental Surgery) Admission", type: "Admission" },
  { title: "Bridge Course for St. Xavier's", type: "Course" },
  { title: "Cosmos College of Management and Technology", type: "College" },
  { title: "Civil Engineering Entrance Preparation", type: "Entrance" },
  { title: "CA (Chartered Accountancy) Institutes", type: "College" },
  { title: "Deerwalk Institute of Technology (DWIT)", type: "College" },
  { title: "DAV College of Management", type: "College" },
  { title: "Diploma in Pharmacy (CTEVT)", type: "Program" },
  { title: "Everest College (+2 & Bachelor)", type: "College" },
  { title: "Engineering Scholarships (IOE Top Rank)", type: "Scholarship" },
  { title: "Executive MBA (EMBA) Programs", type: "Program" },
  { title: "Forestry (BSc. Forestry) Colleges", type: "College" },
  { title: "Foreign University Affiliated IT Colleges", type: "College" },
  { title: "Fine Arts (BFA) Programs in Nepal", type: "Program" },
  { title: "Global College of Management", type: "College" },
  { title: "Gandaki University Admissions", type: "Admission" },
  { title: "Government Quota Scholarships for MBBS", type: "Scholarship" },
  { title: "Herald College Kathmandu (BIT/BBA)", type: "College" },
  { title: "Hotel Management (BHM) Admission Open", type: "Admission" },
  { title: "Humanities & Social Sciences (+2)", type: "Program" },
  { title: "Islington College (IT & Business)", type: "College" },
  { title: "Institute of Medicine (IOM) Entrance", type: "Entrance" },
  { title: "IELTS / TOEFL / SAT Preparation Centers", type: "Course" },
  { title: "Janakpur Engineering College", type: "College" },
  { title: "Journalism and Mass Communication (BAMCJ)", type: "Program" },
  { title: "KUSOM (KU School of Management)", type: "College" },
  { title: "Kathmandu BernHardt College", type: "College" },
  { title: "Khowa / Khwopa Engineering College", type: "College" },
  { title: "Little Angels' College (10+2 & A-Levels)", type: "College" },
  { title: "Lumbini Buddhist University Programs", type: "University" },
  { title: "Law (BA LLB) Entrance Preparation", type: "Entrance" },
  { title: "Morgan International College", type: "College" },
  { title: "MBBS Admission Criteria in Nepal", type: "Admission" },
  { title: "MoE (Ministry of Education) Full Scholarships", type: "Scholarship" },
  { title: "Nepal Engineering College (NEC)", type: "College" },
  { title: "NATHM (National Academy of Tourism & Hotel Management)", type: "College" },
  { title: "Nursing (PCL/BSc) Scholarships", type: "Scholarship" },
  { title: "Optometry (B.Optom) Colleges", type: "College" },
  { title: "Oxford Advanced College", type: "College" },
  { title: "Overseas Study / Study Abroad Counseling", type: "Course" },
  { title: "Pulchowk Campus (IOE Main Campus)", type: "College" },
  { title: "Public Health (BPH) Programs", type: "Program" },
  { title: "PU (Pokhara University) Scholarship Form", type: "Scholarship" },
  { title: "Quest International College", type: "College" },
  { title: "QAA Certified Colleges in Nepal (UGC)", type: "College" },
  { title: "Rato Bangala School (A-Levels)", type: "College" },
  { title: "Radiography (BSc MIT) Colleges", type: "College" },
  { title: "Ritz College of Engineering and Management", type: "College" },
  { title: "St. Xavier's College (Maitighar)", type: "College" },
  { title: "Softwarica College of IT & E-Commerce", type: "College" },
  { title: "Staff Nurse Entrance Preparation", type: "Entrance" },
  { title: "Texas International College", type: "College" },
  { title: "Thames International College", type: "College" },
  { title: "TU (Tribhuvan University) Central Departments", type: "University" },
  { title: "Uniglobe College", type: "College" },
  { title: "UGC (University Grants Commission) Scholarships", type: "Scholarship" },
  { title: "UCEP Nepal (Technical Training)", type: "College" },
  { title: "Valley View College", type: "College" },
  { title: "Veterinary Science (B.VSc & AH) Programs", type: "Program" },
  { title: "Whitehouse International College", type: "College" },
  { title: "Women's Quota Scholarships (CTEVT/TU)", type: "Scholarship" },
  { title: "Xavier International College", type: "College" },
  { title: "Yeti Health Science Academy", type: "College" },
  { title: "Zenith International College", type: "College" },
  { title: "Zoology (BSc/MSc) Programs under TU", type: "Program" }
];

export const trendingSearches: SearchItem[] = [
  { title: "Best +2 Science Colleges in Kathmandu", type: "College" },
  { title: "BIT (Bachelor of Information Technology) Colleges", type: "College" },
  { title: "CMAT Entrance Exam Preparation", type: "Entrance" },
  { title: "+2 Admission Open 2024/2025", type: "Admission" },
  { title: "CTEVT Diploma Colleges in Kathmandu", type: "College" }
];

export const searchIcons: Record<string, string> = {
  "College": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16M9 21v-4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v4M9 7h6M9 11h6M9 15h6"/></svg>`,
  "Program": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/></svg>`,
  "Course": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>`,
  "Scholarship": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"/><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"/></svg>`,
  "Admission": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><path d="M12 18v-6"></path><path d="M9 15h6"></path></svg>`,
  "Entrance": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>`,
  "University": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 10v6M2 10l10-5 10 5-10 5z"></path><path d="M6 12v5c3 3 9 3 12 0v-5"></path></svg>`,
  "Trending": `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"></polyline><polyline points="16 7 22 7 22 13"></polyline></svg>`
};
